image: node:latest

stages:
  - build
  - test

install-client:
  stage: build
  script:
    - cd client
    - npm install
  artifacts:
    paths:
      - ./client/node_modules

install-server:
  stage: build
  script:
    - cd server
    - npm install
  artifacts:
    paths:
      - ./server/node_modules

prettier-client:
  stage: test
  script:
    - ./client/node_modules/.bin/prettier --check client/src/**/*.js client/test/**/*.js

prettier-server:
  stage: test
  script:
    - ./server/node_modules/.bin/prettier --check server/src/**/*.js server/test/**/*.js

flow-client:
  stage: test
  script:
    - cd client
    - ./node_modules/.bin/flow check

flow-server:
  stage: test
  script:
    - cd server
    - ./node_modules/.bin/flow check

test-client:
  stage: test
  script:
    - cd client
    - npm test
test-server:
  stage: test
  script:
    - cd server
    - touch ./src/config.js ./test/config.js #adds empty config files for server test
    - npm test
